### ISSUE TITLE
Support PHP 5.6

### ISSUE THREAD

**Issue by uuf6429** [lbaey/chromedriver#10]
PHP 5.6 is still widely in use and moreover a quick look at the code doesn't seem to use any PHP 7 features, so it's mostly a restriction in the package spec.

**Comment by hackel** [comment]
No, packages need to be aggressive in requiring recent, supported versions of PHP.

https://gophp71.org/

**Comment by uuf6429** [comment]
For the record: I [had a similar discussion](https://goo.gl/HNs5BT), taking your viewpoint, with a member of the Behat core team, where they insisted on supporting **PHP 5.4**, which I saw very unreasonable.

That being said, I believe that any package **should require what it really needs** - and not hold people ransom, especially in this case where *PHP 5.6 is still receiving security updates* by the PHP team.

**Comment by t4k** [comment]
Agreed. I am trying to use ChromeDriver to test all currently supported versions of PHP and this doesn’t work unfortunately.
