### ISSUE TITLE
Platform selection fails

### ISSUE THREAD

**Issue by carstenr** [lbaey/chromedriver#17]
There seems to be an issue with the platform selection during installation. I tried all of the selectable items and get the response: "Platform is not set."

<img width="194" alt="bildschirmfoto 2018-09-12 um 10 13 36" src="https://user-images.githubusercontent.com/2492313/45411493-9b22a280-b674-11e8-83a9-ca52831e12ad.png">

**Comment by carstenr** [comment]
Probably related to https://github.com/lbaey/chromedriver/issues/12

**Comment by rumur** [comment]
@carstenr 
I've managed to install it by adding the extra to composer.json 

`"extra": {
    "lbaey/chromedriver": {
      "bypass-select": true,
      "chromedriver-version": "2.35"
    }
  },`

**Comment by chrillep** [comment]
@lbaey BUMP

**Comment by finnef** [comment]
I had the same problem. rumur's fix helped for me too.
Seems to be the composer single select problem.
